update public.products
set variants = '[]'::jsonb,
    updated_at = now()
where id = 'hello-kitty-plush-12';

update public.products
set variants = '[{"name":"Design","options":[{"label":"My Melody","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/01.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/01.jpg","/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/06.jpg"]},{"label":"Teddy Bear","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/02.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/02.jpg","/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/07.jpg"]},{"label":"Cinnamoroll","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/03.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/03.jpg","/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/08.jpg"]},{"label":"Pink Ribbon","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/04.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/04.jpg"]},{"label":"Bunny","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/05.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/05.jpg"]}]}]'::jsonb,
    images = array['/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/01.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/06.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/02.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/07.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/03.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/08.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/04.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/05.jpg']::text[] || array(select image from unnest(images) as image where not (image = any(array['/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/01.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/06.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/02.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/07.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/03.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/08.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/04.jpg', '/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/05.jpg']::text[]))),
    updated_at = now()
where id = 'laptop-14';

update public.products
set variants = '[{"name":"Design","options":[{"label":"Cherry","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-cherry.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-cherry.jpg"]},{"label":"Pink Peony","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-peony.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-peony.jpg"]},{"label":"Pink Floral","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-floral.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-floral.jpg"]},{"label":"Teddy Bear","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-teddy-bear.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-teddy-bear.jpg"]},{"label":"Springknows","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-springknows.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-springknows.jpg"]},{"label":"Pink Ribbon","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-ribbon.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-ribbon.jpg"]},{"label":"Pink Bowknot","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-bowknot.jpg","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-bowknot.jpg"]}]}]'::jsonb,
    images = array['/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-cherry.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-peony.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-floral.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-teddy-bear.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-springknows.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-ribbon.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-bowknot.jpg']::text[] || array(select image from unnest(images) as image where not (image = any(array['/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-cherry.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-peony.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-floral.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-teddy-bear.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-springknows.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-ribbon.jpg', '/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/variant-pink-bowknot.jpg']::text[]))),
    updated_at = now()
where id = 'makeup-8';

update public.products
set variants = '[{"name":"Color","options":[{"label":"Purple","image":"/assets/products/variant-bouquets/bouquet-16-purple.jpg","images":["/assets/products/variant-bouquets/bouquet-16-purple.jpg"]},{"label":"Pink","image":"/assets/products/variant-bouquets/bouquet-16-pink.jpg","images":["/assets/products/variant-bouquets/bouquet-16-pink.jpg"]},{"label":"Red","image":"/assets/products/variant-bouquets/bouquet-16-red.jpg","images":["/assets/products/variant-bouquets/bouquet-16-red.jpg"]},{"label":"Blue","image":"/assets/products/variant-bouquets/bouquet-16-blue.jpg","images":["/assets/products/variant-bouquets/bouquet-16-blue.jpg"]}]}]'::jsonb,
    images = array['/assets/products/variant-bouquets/bouquet-16-purple.jpg', '/assets/products/variant-bouquets/bouquet-16-pink.jpg', '/assets/products/variant-bouquets/bouquet-16-red.jpg', '/assets/products/variant-bouquets/bouquet-16-blue.jpg']::text[] || array(select image from unnest(images) as image where not (image = any(array['/assets/products/variant-bouquets/bouquet-16-purple.jpg', '/assets/products/variant-bouquets/bouquet-16-pink.jpg', '/assets/products/variant-bouquets/bouquet-16-red.jpg', '/assets/products/variant-bouquets/bouquet-16-blue.jpg']::text[]))),
    updated_at = now()
where id = 'purple-bouquet';

update public.products
set variants = '[{"name":"Color","options":[{"label":"Pink","image":"/assets/products/variant-bouquets/bouquet-small-pink.jpg","images":["/assets/products/variant-bouquets/bouquet-small-pink.jpg"]},{"label":"Red","image":"/assets/products/variant-bouquets/bouquet-small-red.jpg","images":["/assets/products/variant-bouquets/bouquet-small-red.jpg"]}]}]'::jsonb,
    images = array['/assets/products/variant-bouquets/bouquet-small-pink.jpg', '/assets/products/variant-bouquets/bouquet-small-red.jpg']::text[] || array(select image from unnest(images) as image where not (image = any(array['/assets/products/variant-bouquets/bouquet-small-pink.jpg', '/assets/products/variant-bouquets/bouquet-small-red.jpg']::text[]))),
    updated_at = now()
where id = 'small-bouquet';

update public.products
set variants = '[{"name":"Style","options":[{"label":"Snowy Love","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-snowy-love.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-snowy-love.jpg"]},{"label":"Lucky Love","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-lucky-love.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-lucky-love.jpg"]},{"label":"Kitty","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-kitty.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-kitty.jpg"]},{"label":"Circle","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-circle.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-circle.jpg"]},{"label":"Irregular","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-irregular.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-irregular.jpg"]}]}]'::jsonb,
    images = array['/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-snowy-love.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-lucky-love.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-kitty.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-circle.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-irregular.jpg']::text[] || array(select image from unnest(images) as image where not (image = any(array['/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-snowy-love.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-lucky-love.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-kitty.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-circle.jpg', '/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/variant-irregular.jpg']::text[]))),
    updated_at = now()
where id = 'night-light';

update public.products
set variants = '[]'::jsonb,
    updated_at = now()
where id = 'makeup-9';

update public.products
set variants = '[{"name":"Design","options":[{"label":"Pink Floral","image":"/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/01.jpg","images":["/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/01.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/02.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/03.jpg"]},{"label":"Springknows","image":"/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/04.jpg","images":["/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/04.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/05.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/06.jpg"]}]}]'::jsonb,
    images = array['/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/01.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/02.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/03.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/04.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/05.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/06.jpg']::text[] || array(select image from unnest(images) as image where not (image = any(array['/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/01.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/02.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/03.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/04.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/05.jpg', '/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/06.jpg']::text[]))),
    updated_at = now()
where id = 'laptop-12';

update public.products
set variants = '[]'::jsonb,
    updated_at = now()
where id = 'flower-lights-11';
