update public.products
set variants = '[]'::jsonb,
    updated_at = now()
where id = 'hello-kitty-plush-12';

update public.products
set variants = '[{"name":"Design","options":[{"label":"My Melody","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/01.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/01.jpg","/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/06.jpg"]},{"label":"Teddy Bear","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/02.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/02.jpg","/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/07.jpg"]},{"label":"Cinnamoroll","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/03.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/03.jpg","/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/08.jpg"]},{"label":"Pink Ribbon","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/04.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/04.jpg"]},{"label":"Bunny","image":"/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/05.jpg","images":["/assets/products/quilted-floral-laptop-bag-14x10-inches-zipper-closure/05.jpg"]}]}]'::jsonb,
    updated_at = now()
where id = 'laptop-14';

update public.products
set variants = '[{"name":"Design","options":[{"label":"Cherry","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/01.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/01.png"]},{"label":"Pink Peony","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/02.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/02.png"]},{"label":"Pink Floral","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/03.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/03.png"]},{"label":"Teddy Bear","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/04.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/04.png"]},{"label":"Springknows","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/05.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/05.png"]},{"label":"Pink Ribbon","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/06.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/06.png","/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/08.png"]},{"label":"Pink Bowknot","image":"/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/07.png","images":["/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/07.png","/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/09.png","/assets/products/portable-makeup-bag-travel-cosmetic-bag-8-inches/10.png"]}]}]'::jsonb,
    updated_at = now()
where id = 'makeup-8';

update public.products
set variants = '[{"name":"Color","options":[{"label":"Purple","image":"/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/01.jpg","images":["/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/01.jpg","/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/02.jpg","/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/03.jpg"]},{"label":"Pink","image":"/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/04.jpg","images":["/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/04.jpg","/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/05.png"]},{"label":"Red","image":"/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/06.png","images":["/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/06.png","/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/07.jpg"]},{"label":"Blue","image":"/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/08.jpg","images":["/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/08.jpg","/assets/products/crochet-rose-flower-bouquet-gift-for-valentines-day-mothers-day-birthday-wedding-home-decor-handmade-artificial-knitting-flowers-decoration-colorful/09.jpg"]}]}]'::jsonb,
    updated_at = now()
where id = 'purple-bouquet';

update public.products
set variants = '[{"name":"Color","options":[{"label":"Pink","image":"/assets/products/crochet-rose-flower-bouquet-small/01.jpg","images":["/assets/products/crochet-rose-flower-bouquet-small/01.jpg","/assets/products/crochet-rose-flower-bouquet-small/02.jpg","/assets/products/crochet-rose-flower-bouquet-small/03.jpg"]},{"label":"Red","image":"/assets/products/crochet-rose-flower-bouquet-small/04.jpg","images":["/assets/products/crochet-rose-flower-bouquet-small/04.jpg","/assets/products/crochet-rose-flower-bouquet-small/05.jpg","/assets/products/crochet-rose-flower-bouquet-small/06.jpg"]}]}]'::jsonb,
    updated_at = now()
where id = 'small-bouquet';

update public.products
set variants = '[{"name":"Style","options":[{"label":"Snowy Love","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/01.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/01.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/02.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/03.jpg"]},{"label":"Lucky Love","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/04.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/04.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/05.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/06.jpg"]},{"label":"Kitty","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/07.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/07.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/08.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/09.jpg"]},{"label":"Circle","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/10.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/10.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/11.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/12.jpg"]},{"label":"Irregular","image":"/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/13.jpg","images":["/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/13.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/14.jpg","/assets/products/bubblebud-3d-led-night-light-with-erasable-pen/15.jpg"]}]}]'::jsonb,
    updated_at = now()
where id = 'night-light';

update public.products
set variants = '[]'::jsonb,
    updated_at = now()
where id = 'makeup-9';

update public.products
set variants = '[{"name":"Design","options":[{"label":"Pink Floral","image":"/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/01.jpg","images":["/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/01.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/02.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/03.jpg"]},{"label":"Springknows","image":"/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/04.jpg","images":["/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/04.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/05.jpg","/assets/products/quilted-floral-laptop-bag-12x10-inches-zipper-closure/06.jpg"]}]}]'::jsonb,
    updated_at = now()
where id = 'laptop-12';

update public.products
set variants = '[]'::jsonb,
    updated_at = now()
where id = 'flower-lights-11';
